name: Container Create(Build & Push)

on:
  push:
    tags:
      - v*

env:
  GCP_PROJECT: ${{secrets.GCP_PROJECT}}
  ZONE: us.gcr.io
  SA_JSON_KEY: ${{ secrets.SA_JSON_KEY }}
  IMAGE: open-policy-agent

jobs:
  container-create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Container build & Push
        run: |
          echo $SA_JSON_KEY | docker login -u _json_key --password-stdin https://us.gcr.io
          IMAGE_TAG=$(echo ${{ github.ref }} | sed -e "s#refs/tags/v##g")
          docker build -t $ZONE/$GCP_PROJECT/$IMAGE:$IMAGE_TAG -t $ZONE/$GCP_PROJECT/$IMAGE:latest .
          docker push $ZONE/$GCP_PROJECT/$IMAGE:$IMAGE_TAG
          docker push $ZONE/$GCP_PROJECT/$IMAGE:latest